swagger: '2.0'
info:
  description: Lingk NiFi API
  version: '1.0'
  title: Lingk NiFi API - basic auth
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
host: 'ec2-3-81-37-61.compute-1.amazonaws.com:3001'
schemes: 
- https
basePath: /
paths:
  /api/test:
    get:
      produces:
        - 'application/json'
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/MyObject'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
        '500':
          description: Server Error
definitions:
  MyObject:
    properties:
      type:
        type: string
      color:
        type: string
    required:  
      - type
      - color
    #title: Contact

securityDefinitions:
  basic:
    type: basic 

security:
   - basic: []